/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


template <typename T>
class JSI_EXPORT NativeRNMappPluginModuleCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "RNMappPluginModule";

protected:
  NativeRNMappPluginModuleCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeRNMappPluginModuleCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["requestGeofenceLocationPermission"] = MethodMetadata {.argCount = 0, .invoker = __requestGeofenceLocationPermission};
    methodMap_["requestPostNotificationPermission"] = MethodMetadata {.argCount = 0, .invoker = __requestPostNotificationPermission};
    methodMap_["setRemoteMessage"] = MethodMetadata {.argCount = 1, .invoker = __setRemoteMessage};
    methodMap_["isPushFromMapp"] = MethodMetadata {.argCount = 1, .invoker = __isPushFromMapp};
    methodMap_["setToken"] = MethodMetadata {.argCount = 1, .invoker = __setToken};
    methodMap_["getToken"] = MethodMetadata {.argCount = 0, .invoker = __getToken};
    methodMap_["setAlias"] = MethodMetadata {.argCount = 1, .invoker = __setAlias};
    methodMap_["setAliasWithResend"] = MethodMetadata {.argCount = 2, .invoker = __setAliasWithResend};
    methodMap_["getAlias"] = MethodMetadata {.argCount = 0, .invoker = __getAlias};
    methodMap_["engage2"] = MethodMetadata {.argCount = 0, .invoker = __engage2};
    methodMap_["engage"] = MethodMetadata {.argCount = 5, .invoker = __engage};
    methodMap_["engageTestServer"] = MethodMetadata {.argCount = 6, .invoker = __engageTestServer};
    methodMap_["onInitCompletedListener"] = MethodMetadata {.argCount = 0, .invoker = __onInitCompletedListener};
    methodMap_["isReady"] = MethodMetadata {.argCount = 0, .invoker = __isReady};
    methodMap_["setPushEnabled"] = MethodMetadata {.argCount = 1, .invoker = __setPushEnabled};
    methodMap_["isPushEnabled"] = MethodMetadata {.argCount = 0, .invoker = __isPushEnabled};
    methodMap_["setAttributes"] = MethodMetadata {.argCount = 1, .invoker = __setAttributes};
    methodMap_["getAttributes"] = MethodMetadata {.argCount = 1, .invoker = __getAttributes};
    methodMap_["setAttribute"] = MethodMetadata {.argCount = 2, .invoker = __setAttribute};
    methodMap_["setAttributeBoolean"] = MethodMetadata {.argCount = 2, .invoker = __setAttributeBoolean};
    methodMap_["setAttributeInt"] = MethodMetadata {.argCount = 2, .invoker = __setAttributeInt};
    methodMap_["removeAttribute"] = MethodMetadata {.argCount = 1, .invoker = __removeAttribute};
    methodMap_["getAttributeStringValue"] = MethodMetadata {.argCount = 1, .invoker = __getAttributeStringValue};
    methodMap_["addTag"] = MethodMetadata {.argCount = 1, .invoker = __addTag};
    methodMap_["removeTag"] = MethodMetadata {.argCount = 1, .invoker = __removeTag};
    methodMap_["getTags"] = MethodMetadata {.argCount = 0, .invoker = __getTags};
    methodMap_["getDeviceInfo"] = MethodMetadata {.argCount = 0, .invoker = __getDeviceInfo};
    methodMap_["getDeviceDmcInfo"] = MethodMetadata {.argCount = 0, .invoker = __getDeviceDmcInfo};
    methodMap_["isDeviceRegistered"] = MethodMetadata {.argCount = 0, .invoker = __isDeviceRegistered};
    methodMap_["lockScreenOrientation"] = MethodMetadata {.argCount = 1, .invoker = __lockScreenOrientation};
    methodMap_["removeBadgeNumber"] = MethodMetadata {.argCount = 0, .invoker = __removeBadgeNumber};
    methodMap_["startGeofencing"] = MethodMetadata {.argCount = 0, .invoker = __startGeofencing};
    methodMap_["stopGeofencing"] = MethodMetadata {.argCount = 0, .invoker = __stopGeofencing};
    methodMap_["startGeoFencing"] = MethodMetadata {.argCount = 0, .invoker = __startGeoFencing};
    methodMap_["stopGeoFencing"] = MethodMetadata {.argCount = 0, .invoker = __stopGeoFencing};
    methodMap_["fetchLatestInboxMessage"] = MethodMetadata {.argCount = 0, .invoker = __fetchLatestInboxMessage};
    methodMap_["fetchInboxMessage"] = MethodMetadata {.argCount = 0, .invoker = __fetchInboxMessage};
    methodMap_["triggerInApp"] = MethodMetadata {.argCount = 1, .invoker = __triggerInApp};
    methodMap_["inAppMarkAsRead"] = MethodMetadata {.argCount = 2, .invoker = __inAppMarkAsRead};
    methodMap_["inAppMarkAsUnRead"] = MethodMetadata {.argCount = 2, .invoker = __inAppMarkAsUnRead};
    methodMap_["inAppMarkAsDeleted"] = MethodMetadata {.argCount = 2, .invoker = __inAppMarkAsDeleted};
    methodMap_["triggerStatistic"] = MethodMetadata {.argCount = 6, .invoker = __triggerStatistic};
    methodMap_["addAndroidListener"] = MethodMetadata {.argCount = 1, .invoker = __addAndroidListener};
    methodMap_["removeAndroidListeners"] = MethodMetadata {.argCount = 1, .invoker = __removeAndroidListeners};
    methodMap_["addListener"] = MethodMetadata {.argCount = 1, .invoker = __addListener};
    methodMap_["removeListeners"] = MethodMetadata {.argCount = 1, .invoker = __removeListeners};
    methodMap_["clearNotifications"] = MethodMetadata {.argCount = 0, .invoker = __clearNotifications};
    methodMap_["clearNotification"] = MethodMetadata {.argCount = 1, .invoker = __clearNotification};
    methodMap_["logOut"] = MethodMetadata {.argCount = 1, .invoker = __logOut};
  }
  
private:
  static jsi::Value __requestGeofenceLocationPermission(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::requestGeofenceLocationPermission) == 1,
      "Expected requestGeofenceLocationPermission(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::requestGeofenceLocationPermission,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __requestPostNotificationPermission(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::requestPostNotificationPermission) == 1,
      "Expected requestPostNotificationPermission(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::requestPostNotificationPermission,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __setRemoteMessage(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::setRemoteMessage) == 2,
      "Expected setRemoteMessage(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::setRemoteMessage,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));
  }

  static jsi::Value __isPushFromMapp(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::isPushFromMapp) == 2,
      "Expected isPushFromMapp(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::isPushFromMapp,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));
  }

  static jsi::Value __setToken(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::setToken) == 2,
      "Expected setToken(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::setToken,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));
  }

  static jsi::Value __getToken(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getToken) == 1,
      "Expected getToken(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getToken,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __setAlias(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::setAlias) == 2,
      "Expected setAlias(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::setAlias,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));
  }

  static jsi::Value __setAliasWithResend(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::setAliasWithResend) == 3,
      "Expected setAliasWithResend(...) to have 3 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::setAliasWithResend,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asBool());
  }

  static jsi::Value __getAlias(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getAlias) == 1,
      "Expected getAlias(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getAlias,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __engage2(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::engage2) == 1,
      "Expected engage2(...) to have 1 parameters");
    bridging::callFromJs<void>(rt, &T::engage2,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));return jsi::Value::undefined();
  }

  static jsi::Value __engage(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::engage) == 6,
      "Expected engage(...) to have 6 parameters");
    bridging::callFromJs<void>(rt, &T::engage,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt),
      count <= 2 ? throw jsi::JSError(rt, "Expected argument in position 2 to be passed") : args[2].asString(rt),
      count <= 3 ? throw jsi::JSError(rt, "Expected argument in position 3 to be passed") : args[3].asString(rt),
      count <= 4 ? throw jsi::JSError(rt, "Expected argument in position 4 to be passed") : args[4].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __engageTestServer(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::engageTestServer) == 7,
      "Expected engageTestServer(...) to have 7 parameters");
    bridging::callFromJs<void>(rt, &T::engageTestServer,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt),
      count <= 2 ? throw jsi::JSError(rt, "Expected argument in position 2 to be passed") : args[2].asString(rt),
      count <= 3 ? throw jsi::JSError(rt, "Expected argument in position 3 to be passed") : args[3].asString(rt),
      count <= 4 ? throw jsi::JSError(rt, "Expected argument in position 4 to be passed") : args[4].asString(rt),
      count <= 5 ? throw jsi::JSError(rt, "Expected argument in position 5 to be passed") : args[5].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __onInitCompletedListener(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::onInitCompletedListener) == 1,
      "Expected onInitCompletedListener(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::onInitCompletedListener,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __isReady(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::isReady) == 1,
      "Expected isReady(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::isReady,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __setPushEnabled(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::setPushEnabled) == 2,
      "Expected setPushEnabled(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::setPushEnabled,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asBool());return jsi::Value::undefined();
  }

  static jsi::Value __isPushEnabled(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::isPushEnabled) == 1,
      "Expected isPushEnabled(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::isPushEnabled,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __setAttributes(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::setAttributes) == 2,
      "Expected setAttributes(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::setAttributes,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt));
  }

  static jsi::Value __getAttributes(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::getAttributes) == 2,
      "Expected getAttributes(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getAttributes,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt).asArray(rt));
  }

  static jsi::Value __setAttribute(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::setAttribute) == 3,
      "Expected setAttribute(...) to have 3 parameters");
    bridging::callFromJs<void>(rt, &T::setAttribute,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __setAttributeBoolean(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::setAttributeBoolean) == 3,
      "Expected setAttributeBoolean(...) to have 3 parameters");
    bridging::callFromJs<void>(rt, &T::setAttributeBoolean,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asBool());return jsi::Value::undefined();
  }

  static jsi::Value __setAttributeInt(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::setAttributeInt) == 3,
      "Expected setAttributeInt(...) to have 3 parameters");
    bridging::callFromJs<void>(rt, &T::setAttributeInt,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asNumber());return jsi::Value::undefined();
  }

  static jsi::Value __removeAttribute(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::removeAttribute) == 2,
      "Expected removeAttribute(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::removeAttribute,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __getAttributeStringValue(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::getAttributeStringValue) == 2,
      "Expected getAttributeStringValue(...) to have 2 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getAttributeStringValue,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));
  }

  static jsi::Value __addTag(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::addTag) == 2,
      "Expected addTag(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::addTag,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __removeTag(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::removeTag) == 2,
      "Expected removeTag(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::removeTag,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __getTags(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getTags) == 1,
      "Expected getTags(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getTags,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __getDeviceInfo(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getDeviceInfo) == 1,
      "Expected getDeviceInfo(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getDeviceInfo,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __getDeviceDmcInfo(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getDeviceDmcInfo) == 1,
      "Expected getDeviceDmcInfo(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getDeviceDmcInfo,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __isDeviceRegistered(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::isDeviceRegistered) == 1,
      "Expected isDeviceRegistered(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::isDeviceRegistered,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __lockScreenOrientation(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::lockScreenOrientation) == 2,
      "Expected lockScreenOrientation(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::lockScreenOrientation,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber());return jsi::Value::undefined();
  }

  static jsi::Value __removeBadgeNumber(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::removeBadgeNumber) == 1,
      "Expected removeBadgeNumber(...) to have 1 parameters");
    bridging::callFromJs<void>(rt, &T::removeBadgeNumber,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));return jsi::Value::undefined();
  }

  static jsi::Value __startGeofencing(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::startGeofencing) == 1,
      "Expected startGeofencing(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::startGeofencing,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __stopGeofencing(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::stopGeofencing) == 1,
      "Expected stopGeofencing(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::stopGeofencing,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __startGeoFencing(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::startGeoFencing) == 1,
      "Expected startGeoFencing(...) to have 1 parameters");
    bridging::callFromJs<void>(rt, &T::startGeoFencing,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));return jsi::Value::undefined();
  }

  static jsi::Value __stopGeoFencing(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::stopGeoFencing) == 1,
      "Expected stopGeoFencing(...) to have 1 parameters");
    bridging::callFromJs<void>(rt, &T::stopGeoFencing,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));return jsi::Value::undefined();
  }

  static jsi::Value __fetchLatestInboxMessage(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::fetchLatestInboxMessage) == 1,
      "Expected fetchLatestInboxMessage(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::fetchLatestInboxMessage,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __fetchInboxMessage(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::fetchInboxMessage) == 1,
      "Expected fetchInboxMessage(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::fetchInboxMessage,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __triggerInApp(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::triggerInApp) == 2,
      "Expected triggerInApp(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::triggerInApp,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __inAppMarkAsRead(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::inAppMarkAsRead) == 3,
      "Expected inAppMarkAsRead(...) to have 3 parameters");
    bridging::callFromJs<void>(rt, &T::inAppMarkAsRead,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber(),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __inAppMarkAsUnRead(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::inAppMarkAsUnRead) == 3,
      "Expected inAppMarkAsUnRead(...) to have 3 parameters");
    bridging::callFromJs<void>(rt, &T::inAppMarkAsUnRead,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber(),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __inAppMarkAsDeleted(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::inAppMarkAsDeleted) == 3,
      "Expected inAppMarkAsDeleted(...) to have 3 parameters");
    bridging::callFromJs<void>(rt, &T::inAppMarkAsDeleted,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber(),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __triggerStatistic(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::triggerStatistic) == 7,
      "Expected triggerStatistic(...) to have 7 parameters");
    bridging::callFromJs<void>(rt, &T::triggerStatistic,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber(),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt),
      count <= 2 ? throw jsi::JSError(rt, "Expected argument in position 2 to be passed") : args[2].asString(rt),
      count <= 3 ? throw jsi::JSError(rt, "Expected argument in position 3 to be passed") : args[3].asNumber(),
      count <= 4 ? throw jsi::JSError(rt, "Expected argument in position 4 to be passed") : args[4].asString(rt),
      count <= 5 ? throw jsi::JSError(rt, "Expected argument in position 5 to be passed") : args[5].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __addAndroidListener(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::addAndroidListener) == 2,
      "Expected addAndroidListener(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::addAndroidListener,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __removeAndroidListeners(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::removeAndroidListeners) == 2,
      "Expected removeAndroidListeners(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::removeAndroidListeners,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber());return jsi::Value::undefined();
  }

  static jsi::Value __addListener(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::addListener) == 2,
      "Expected addListener(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::addListener,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __removeListeners(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::removeListeners) == 2,
      "Expected removeListeners(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::removeListeners,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber());return jsi::Value::undefined();
  }

  static jsi::Value __clearNotifications(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::clearNotifications) == 1,
      "Expected clearNotifications(...) to have 1 parameters");
    bridging::callFromJs<void>(rt, &T::clearNotifications,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));return jsi::Value::undefined();
  }

  static jsi::Value __clearNotification(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::clearNotification) == 2,
      "Expected clearNotification(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::clearNotification,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber());return jsi::Value::undefined();
  }

  static jsi::Value __logOut(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::logOut) == 2,
      "Expected logOut(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::logOut,  static_cast<NativeRNMappPluginModuleCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asBool());return jsi::Value::undefined();
  }
};

} // namespace facebook::react
