
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "RNMappPlugin.h"

namespace facebook::react {

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_requestGeofenceLocationPermission(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "requestGeofenceLocationPermission", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_requestPostNotificationPermission(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "requestPostNotificationPermission", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_setRemoteMessage(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setRemoteMessage", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_isPushFromMapp(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "isPushFromMapp", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_setToken(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setToken", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_getToken(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getToken", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_setAlias(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setAlias", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_setAliasWithResend(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setAliasWithResend", "(Ljava/lang/String;ZLcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_getAlias(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getAlias", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_engage2(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "engage2", "()V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_engage(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "engage", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_engageTestServer(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "engageTestServer", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_onInitCompletedListener(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "onInitCompletedListener", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_isReady(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "isReady", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_setPushEnabled(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "setPushEnabled", "(Z)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_isPushEnabled(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "isPushEnabled", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_setAttributes(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setAttributes", "(Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_getAttributes(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getAttributes", "(Lcom/facebook/react/bridge/ReadableArray;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_setAttribute(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "setAttribute", "(Ljava/lang/String;Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_setAttributeBoolean(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "setAttributeBoolean", "(Ljava/lang/String;Z)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_setAttributeInt(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "setAttributeInt", "(Ljava/lang/String;D)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_removeAttribute(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "removeAttribute", "(Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_getAttributeStringValue(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getAttributeStringValue", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_addTag(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "addTag", "(Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_removeTag(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "removeTag", "(Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_getTags(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getTags", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_getDeviceInfo(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getDeviceInfo", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_getDeviceDmcInfo(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getDeviceDmcInfo", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_isDeviceRegistered(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "isDeviceRegistered", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_lockScreenOrientation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "lockScreenOrientation", "(D)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_removeBadgeNumber(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "removeBadgeNumber", "()V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_startGeofencing(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "startGeofencing", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_stopGeofencing(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "stopGeofencing", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_startGeoFencing(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "startGeoFencing", "()V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_stopGeoFencing(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "stopGeoFencing", "()V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_fetchLatestInboxMessage(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "fetchLatestInboxMessage", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_fetchInboxMessage(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "fetchInboxMessage", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_triggerInApp(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "triggerInApp", "(Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_inAppMarkAsRead(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "inAppMarkAsRead", "(DLjava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_inAppMarkAsUnRead(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "inAppMarkAsUnRead", "(DLjava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_inAppMarkAsDeleted(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "inAppMarkAsDeleted", "(DLjava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_triggerStatistic(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "triggerStatistic", "(DLjava/lang/String;Ljava/lang/String;DLjava/lang/String;Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_addAndroidListener(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "addAndroidListener", "(Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_removeAndroidListeners(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "removeAndroidListeners", "(D)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_addListener(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "addListener", "(Ljava/lang/String;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_removeListeners(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "removeListeners", "(D)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_clearNotifications(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "clearNotifications", "()V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_clearNotification(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "clearNotification", "(D)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMappPluginModuleSpecJSI_logOut(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "logOut", "(Z)V", args, count, cachedMethodId);
}

NativeRNMappPluginModuleSpecJSI::NativeRNMappPluginModuleSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["requestGeofenceLocationPermission"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_requestGeofenceLocationPermission};
  methodMap_["requestPostNotificationPermission"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_requestPostNotificationPermission};
  methodMap_["setRemoteMessage"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_setRemoteMessage};
  methodMap_["isPushFromMapp"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_isPushFromMapp};
  methodMap_["setToken"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_setToken};
  methodMap_["getToken"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_getToken};
  methodMap_["setAlias"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_setAlias};
  methodMap_["setAliasWithResend"] = MethodMetadata {2, __hostFunction_NativeRNMappPluginModuleSpecJSI_setAliasWithResend};
  methodMap_["getAlias"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_getAlias};
  methodMap_["engage2"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_engage2};
  methodMap_["engage"] = MethodMetadata {5, __hostFunction_NativeRNMappPluginModuleSpecJSI_engage};
  methodMap_["engageTestServer"] = MethodMetadata {6, __hostFunction_NativeRNMappPluginModuleSpecJSI_engageTestServer};
  methodMap_["onInitCompletedListener"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_onInitCompletedListener};
  methodMap_["isReady"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_isReady};
  methodMap_["setPushEnabled"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_setPushEnabled};
  methodMap_["isPushEnabled"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_isPushEnabled};
  methodMap_["setAttributes"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_setAttributes};
  methodMap_["getAttributes"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_getAttributes};
  methodMap_["setAttribute"] = MethodMetadata {2, __hostFunction_NativeRNMappPluginModuleSpecJSI_setAttribute};
  methodMap_["setAttributeBoolean"] = MethodMetadata {2, __hostFunction_NativeRNMappPluginModuleSpecJSI_setAttributeBoolean};
  methodMap_["setAttributeInt"] = MethodMetadata {2, __hostFunction_NativeRNMappPluginModuleSpecJSI_setAttributeInt};
  methodMap_["removeAttribute"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_removeAttribute};
  methodMap_["getAttributeStringValue"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_getAttributeStringValue};
  methodMap_["addTag"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_addTag};
  methodMap_["removeTag"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_removeTag};
  methodMap_["getTags"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_getTags};
  methodMap_["getDeviceInfo"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_getDeviceInfo};
  methodMap_["getDeviceDmcInfo"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_getDeviceDmcInfo};
  methodMap_["isDeviceRegistered"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_isDeviceRegistered};
  methodMap_["lockScreenOrientation"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_lockScreenOrientation};
  methodMap_["removeBadgeNumber"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_removeBadgeNumber};
  methodMap_["startGeofencing"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_startGeofencing};
  methodMap_["stopGeofencing"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_stopGeofencing};
  methodMap_["startGeoFencing"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_startGeoFencing};
  methodMap_["stopGeoFencing"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_stopGeoFencing};
  methodMap_["fetchLatestInboxMessage"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_fetchLatestInboxMessage};
  methodMap_["fetchInboxMessage"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_fetchInboxMessage};
  methodMap_["triggerInApp"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_triggerInApp};
  methodMap_["inAppMarkAsRead"] = MethodMetadata {2, __hostFunction_NativeRNMappPluginModuleSpecJSI_inAppMarkAsRead};
  methodMap_["inAppMarkAsUnRead"] = MethodMetadata {2, __hostFunction_NativeRNMappPluginModuleSpecJSI_inAppMarkAsUnRead};
  methodMap_["inAppMarkAsDeleted"] = MethodMetadata {2, __hostFunction_NativeRNMappPluginModuleSpecJSI_inAppMarkAsDeleted};
  methodMap_["triggerStatistic"] = MethodMetadata {6, __hostFunction_NativeRNMappPluginModuleSpecJSI_triggerStatistic};
  methodMap_["addAndroidListener"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_addAndroidListener};
  methodMap_["removeAndroidListeners"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_removeAndroidListeners};
  methodMap_["addListener"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_addListener};
  methodMap_["removeListeners"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_removeListeners};
  methodMap_["clearNotifications"] = MethodMetadata {0, __hostFunction_NativeRNMappPluginModuleSpecJSI_clearNotifications};
  methodMap_["clearNotification"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_clearNotification};
  methodMap_["logOut"] = MethodMetadata {1, __hostFunction_NativeRNMappPluginModuleSpecJSI_logOut};
}

std::shared_ptr<TurboModule> RNMappPlugin_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  if (moduleName == "RNMappPluginModule") {
    return std::make_shared<NativeRNMappPluginModuleSpecJSI>(params);
  }
  return nullptr;
}

} // namespace facebook::react
