
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.reactlibrary;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeRNMappPluginModuleSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "RNMappPluginModule";

  public NativeRNMappPluginModuleSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void requestGeofenceLocationPermission(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void requestPostNotificationPermission(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setRemoteMessage(String msgJson, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void isPushFromMapp(String msgJson, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setToken(String token, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getToken(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setAlias(String alias, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setAliasWithResend(String alias, boolean resendCustomAttributes, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getAlias(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void engage2();

  @ReactMethod
  @DoNotStrip
  public abstract void engage(String sdkKey, String googleProjectId, String server, String appID, String tenantID);

  @ReactMethod
  @DoNotStrip
  public abstract void engageTestServer(String cepURl, String sdkKey, String googleProjectId, String server, String appID, String tenantID);

  @ReactMethod
  @DoNotStrip
  public abstract void onInitCompletedListener(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void isReady(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setPushEnabled(boolean optIn);

  @ReactMethod
  @DoNotStrip
  public abstract void isPushEnabled(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setAttributes(ReadableMap attributes, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getAttributes(ReadableArray keys, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setAttribute(String key, String value);

  @ReactMethod
  @DoNotStrip
  public abstract void setAttributeBoolean(String key, boolean value);

  @ReactMethod
  @DoNotStrip
  public abstract void setAttributeInt(String key, double value);

  @ReactMethod
  @DoNotStrip
  public abstract void removeAttribute(String attribute);

  @ReactMethod
  @DoNotStrip
  public abstract void getAttributeStringValue(String key, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void addTag(String tag);

  @ReactMethod
  @DoNotStrip
  public abstract void removeTag(String tag);

  @ReactMethod
  @DoNotStrip
  public abstract void getTags(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getDeviceInfo(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getDeviceDmcInfo(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void isDeviceRegistered(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void lockScreenOrientation(double orientation);

  @ReactMethod
  @DoNotStrip
  public abstract void removeBadgeNumber();

  @ReactMethod
  @DoNotStrip
  public abstract void startGeofencing(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void stopGeofencing(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void startGeoFencing();

  @ReactMethod
  @DoNotStrip
  public abstract void stopGeoFencing();

  @ReactMethod
  @DoNotStrip
  public abstract void fetchLatestInboxMessage(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void fetchInboxMessage(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void triggerInApp(String key);

  @ReactMethod
  @DoNotStrip
  public abstract void inAppMarkAsRead(double templateId, String eventId);

  @ReactMethod
  @DoNotStrip
  public abstract void inAppMarkAsUnRead(double templateId, String eventId);

  @ReactMethod
  @DoNotStrip
  public abstract void inAppMarkAsDeleted(double templateId, String eventId);

  @ReactMethod
  @DoNotStrip
  public abstract void triggerStatistic(double templateId, String originalEventId, String trackingKey, double displayMillis, String reason, String link);

  @ReactMethod
  @DoNotStrip
  public abstract void addAndroidListener(String eventName);

  @ReactMethod
  @DoNotStrip
  public abstract void removeAndroidListeners(double count);

  @ReactMethod
  @DoNotStrip
  public abstract void addListener(String eventName);

  @ReactMethod
  @DoNotStrip
  public abstract void removeListeners(double count);

  @ReactMethod
  @DoNotStrip
  public abstract void clearNotifications();

  @ReactMethod
  @DoNotStrip
  public abstract void clearNotification(double id);

  @ReactMethod
  @DoNotStrip
  public abstract void logOut(boolean pushEnabled);
}
